"use strict";
const $=id=>document.getElementById(id), canvas=$("canvas"), ctx=canvas.getContext("2d"), frame=$("canvas-frame");
let records=[],filtered=[],position=0,current=null,image=null,quads=[],selected=0,drag=null,zoom=1,fitScale=1,dirty=false,addPoints=[];
const statusText={pending:"待審核",accepted:"接受",excluded:"排除"};

async function api(url,options){const response=await fetch(url,options);const data=await response.json();if(!response.ok)throw new Error(data.error||response.statusText);return data}
function clone(v){return JSON.parse(JSON.stringify(v))}
function counts(){for(const s of ["pending","accepted","excluded"])$(s+"-count").textContent=records.filter(r=>r.review_status===s).length;$("all-count").textContent=records.length;const done=records.filter(r=>r.review_status!=="pending").length;$("progress-bar").style.width=`${done/records.length*100}%`}
function applyFilter(name){document.querySelectorAll(".filter").forEach(b=>b.classList.toggle("active",b.dataset.filter===name));filtered=records.filter(r=>name==="all"||r.review_status===name);position=Math.min(position,Math.max(0,filtered.length-1));loadCurrent()}
async function loadCurrent(){if(!filtered.length){current=null;ctx.clearRect(0,0,canvas.width,canvas.height);$("loading").textContent="此分類沒有影像";$("loading").hidden=false;return}current=filtered[position];quads=clone(current.reviewed_corners);selected=Math.min(selected,Math.max(0,quads.length-1));dirty=false;addPoints=[];$("loading").hidden=false;$("loading").textContent="載入影像…";const img=new Image();img.onload=()=>{image=img;fit();$("loading").hidden=true;render()};img.src=`/api/image/${current.validation_index}?v=${Date.now()}`;updateInspector()}
function fit(){if(!image)return;fitScale=Math.min((frame.clientWidth-24)/image.width,(frame.clientHeight-24)/image.height);zoom=1;resizeCanvas()}
function resizeCanvas(){if(!image)return;const scale=fitScale*zoom;canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.dataset.scale=scale;$("zoom-label").textContent=`${Math.round(zoom*100)}%`;render()}
function render(){if(!image)return;const s=Number(canvas.dataset.scale);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);ctx.lineJoin="round";quads.forEach((quad,i)=>{ctx.beginPath();quad.forEach((p,j)=>{const x=p[0]*s,y=p[1]*s;j?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.strokeStyle=i===selected?"#ff9d22":"#57a8ff";ctx.lineWidth=i===selected?3:2;ctx.stroke();quad.forEach((p,j)=>{ctx.beginPath();ctx.arc(p[0]*s,p[1]*s,i===selected?7:5,0,Math.PI*2);ctx.fillStyle=i===selected?"#ff9d22":"#57a8ff";ctx.fill();ctx.strokeStyle="#101820";ctx.lineWidth=2;ctx.stroke();ctx.fillStyle="#08111e";ctx.font="bold 10px Segoe UI";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(String(j+1),p[0]*s,p[1]*s)})});if(addPoints.length){ctx.strokeStyle="#ffd28a";ctx.lineWidth=2;ctx.beginPath();addPoints.forEach((p,j)=>j?ctx.lineTo(p[0]*s,p[1]*s):ctx.moveTo(p[0]*s,p[1]*s));ctx.stroke();addPoints.forEach(p=>{ctx.beginPath();ctx.arc(p[0]*s,p[1]*s,6,0,Math.PI*2);ctx.fillStyle="#ffd28a";ctx.fill()})}$("reviewed-count").textContent=quads.length}
function updateInspector(){if(!current)return;$("progress").textContent=`${position+1} / ${filtered.length}`;$("validation-index").textContent=current.validation_index;$("size-bucket").textContent=current.size_bucket;$("rotation-deg").textContent=`${current.rotation_deg.toFixed(1)}°`;$("image-sha").textContent=current.image_sha256.slice(0,12);$("short-side").textContent=`${current.bbox_short_side_640px.toFixed(1)} px`;$("original-count").textContent=current.original_count;$("reviewed-count").textContent=quads.length;$("image-size").textContent=current.image_size_wh.join(" × ");$("exclude-reason").value=current.exclude_reason||"";$("reviewer-note").value=current.reviewer_note||"";const st=$("status");st.textContent=statusText[current.review_status];st.className=`status ${current.review_status}`;$("save-state").textContent=dirty?"有未儲存修改":"已同步";counts()}
function pointerPoint(event){const rect=canvas.getBoundingClientRect(),s=Number(canvas.dataset.scale);return[(event.clientX-rect.left)/s,(event.clientY-rect.top)/s]}
function nearest(point){const s=Number(canvas.dataset.scale),limit=14/s;let best=null,distance=Infinity;quads.forEach((q,qi)=>q.forEach((p,pi)=>{const d=Math.hypot(p[0]-point[0],p[1]-point[1]);if(d<distance&&d<=limit){best=[qi,pi];distance=d}}));return best}
canvas.addEventListener("pointerdown",e=>{const p=pointerPoint(e);if(addPoints.length||canvas.dataset.adding==="1"){addPoints.push(p);if(addPoints.length===4){quads.push(addPoints);selected=quads.length-1;addPoints=[];canvas.dataset.adding="0";dirty=true;updateInspector()}render();return}const hit=nearest(p);if(hit){selected=hit[0];drag=hit;canvas.setPointerCapture(e.pointerId);render()}});
canvas.addEventListener("pointermove",e=>{if(!drag)return;const p=pointerPoint(e);quads[drag[0]][drag[1]]=[Math.max(0,Math.min(image.width-1,p[0])),Math.max(0,Math.min(image.height-1,p[1]))];markDirty();render()});
canvas.addEventListener("pointerup",()=>drag=null);
function markDirty(){dirty=true;$("save-state").textContent="有未儲存修改";$("reviewed-count").textContent=quads.length}
async function save(status){if(!current)return;const reason=$("exclude-reason").value||null;if(status==="excluded"&&!reason){alert("請先選擇排除原因");return}try{$("save-state").textContent="儲存中…";const result=await api(`/api/review/${current.validation_index}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({review_status:status,exclude_reason:status==="excluded"?reason:null,reviewer_note:$("reviewer-note").value,reviewed_corners:quads})});current.review_status=status;current.exclude_reason=status==="excluded"?reason:null;current.reviewer_note=$("reviewer-note").value;current.reviewed_corners=clone(quads);current.reviewed_count=quads.length;current.reviewed_at=result.reviewed_at;dirty=false;counts();applyFilter(document.querySelector(".filter.active").dataset.filter)}catch(error){alert(error.message);$("save-state").textContent="儲存失敗"}}
async function navigate(delta){if(dirty)await save("pending");if(!filtered.length)return;position=(position+delta+filtered.length)%filtered.length;loadCurrent()}
$("previous").onclick=()=>navigate(-1);$("next").onclick=()=>navigate(1);$("accept").onclick=()=>save("accepted");$("exclude").onclick=()=>save("excluded");
$("add-plate").onclick=()=>{canvas.dataset.adding="1";addPoints=[];$("edit-hint").textContent="依序點選 LT → RT → RB → LB；Esc 取消"};
$("delete-plate").onclick=()=>{if(quads.length&&confirm("刪除目前選取的車牌標註？")){quads.splice(selected,1);selected=Math.max(0,selected-1);markDirty();render()}};
$("reset").onclick=()=>{if(confirm("回復這張影像的原始標註？")){quads=clone(current.original_corners);selected=0;markDirty();render()}};
$("zoom-in").onclick=()=>{zoom=Math.min(3,zoom+.25);resizeCanvas()};$("zoom-out").onclick=()=>{zoom=Math.max(.5,zoom-.25);resizeCanvas()};$("fit").onclick=fit;
$("reviewer-note").oninput=markDirty;$("exclude-reason").onchange=markDirty;document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>applyFilter(b.dataset.filter));
window.addEventListener("resize",fit);window.addEventListener("keydown",e=>{if(e.target.matches("textarea,select"))return;if(e.key==="Escape"){addPoints=[];canvas.dataset.adding="0";render()}else if(e.key==="ArrowLeft")navigate(-1);else if(e.key==="ArrowRight")navigate(1);else if(e.key.toLowerCase()==="a")save("accepted");else if(e.key.toLowerCase()==="x")save("excluded");else if(e.key.toLowerCase()==="n")$("add-plate").click();else if(e.key.toLowerCase()==="d")$("delete-plate").click();else if(e.key.toLowerCase()==="r")$("reset").click()});

api("/api/state").then(data=>{records=data.records;counts();applyFilter("pending")}).catch(error=>{$("loading").textContent=`載入失敗：${error.message}`});
